### ISSUE TITLE
Not working in Spigot 1.9

### ISSUE THREAD

**Issue by Rhmul** [jdon/Ticket-Man#2]
Gives me this console error when trying to load the plugin http://pastebin.com/ntdxgcLe

**Comment by Pigna** [comment]
Are you missing the plugin SQLLibrary?
http://dev.bukkit.org/bukkit-plugins/sqlibrary/

It needs this plugin to function.

**Comment by Rhmul** [comment]
No I did not have that plugin, thanks so much.

**Comment by Rhmul** [comment]
Now that I got a config file it wont save the password for the database.

**Comment by Rhmul** [comment]
It saves the rest of the info, just keeps resetting the password back to "password"

**Comment by Pigna** [comment]
I'm having an issue also with connection. But for me it just says connection refused becouse to many incorrect attemptes on connecting to the database. Could have somthing to do with your issue. But gota ask host to clear the logg first to make sure.

My config is build like this:
http://pastebin.com/rmTjDVU9
Dont mind the [ ] they just show its a variable.

**Comment by jdon** [comment]
if the connection is refused then it is because the mysql server is refusing them.

I have tested this plugin on the latested build of bukkit and the passwords seems to saving for me, do you have any other errors?

Edit: Closed this issue, since I got no reply
